import json
import sys
from pathlib import Path

import pandas as pd


def build_dashboard_data(csv_path: str):
    df = pd.read_csv(csv_path)
    df["date"] = pd.to_datetime(df["date"])
    df["month"] = df["date"].dt.to_period("M").astype(str)

    revenue = float(df["revenue"].sum())
    cost = float(df["cost"].sum())
    gross_profit = float(df["gross_profit"].sum())

    monthly = (
        df.groupby("month", as_index=False)
        .agg(
            revenue=("revenue", "sum"),
            gross_profit=("gross_profit", "sum"),
        )
    )
    monthly["gross_margin_pct"] = monthly["gross_profit"] / monthly["revenue"] * 100
    monthly["growth_pct"] = monthly["revenue"].pct_change().fillna(0)

    countries = (
        df.groupby("country", as_index=False)
        .agg(revenue=("revenue", "sum"), gross_profit=("gross_profit", "sum"))
        .sort_values("revenue", ascending=False)
    )
    countries["share_pct"] = countries["revenue"] / revenue * 100

    products = (
        df.groupby("product", as_index=False)
        .agg(revenue=("revenue", "sum"), gross_profit=("gross_profit", "sum"))
    )
    products["gross_margin_pct"] = products["gross_profit"] / products["revenue"] * 100
    products = products.sort_values("revenue", ascending=False)

    customers = (
        df.groupby("customer_name", as_index=False)["revenue"]
        .sum()
        .sort_values("revenue", ascending=False)
    )
    customers["share_pct"] = customers["revenue"] / revenue * 100

    payments = (
        df.groupby("payment_status", as_index=False)["revenue"]
        .sum()
        .sort_values("revenue", ascending=False)
    )
    payments["share_pct"] = payments["revenue"] / revenue * 100

    return {
        "executive": {
            "totalRevenue": round(revenue, 2),
            "totalCost": round(cost, 2),
            "grossProfit": round(gross_profit, 2),
            "grossMarginPct": round(gross_profit / revenue * 100, 2),
            "transactions": int(len(df)),
            "customers": int(df["customer_name"].nunique()),
            "unitsSold": int(df["quantity"].sum()),
        },
        "monthlyPerformance": [
            {
                "month": row["month"],
                "revenue": round(float(row["revenue"]), 2),
                "grossProfit": round(float(row["gross_profit"]), 2),
                "grossMarginPct": round(float(row["gross_margin_pct"]), 2),
                "growthPct": round(float(row["growth_pct"]), 2),
            }
            for _, row in monthly.iterrows()
        ],
        "countries": [
            {
                "name": row["country"],
                "revenue": round(float(row["revenue"]), 2),
                "sharePct": round(float(row["share_pct"]), 2),
            }
            for _, row in countries.iterrows()
        ],
        "products": [
            {
                "name": row["product"],
                "revenue": round(float(row["revenue"]), 2),
                "grossProfit": round(float(row["gross_profit"]), 2),
                "grossMarginPct": round(float(row["gross_margin_pct"]), 2),
            }
            for _, row in products.iterrows()
        ],
        "customers": [
            {
                "name": row["customer_name"],
                "revenue": round(float(row["revenue"]), 2),
                "sharePct": round(float(row["share_pct"]), 2),
            }
            for _, row in customers.head(15).iterrows()
        ],
        "payments": [
            {
                "status": row["payment_status"],
                "revenue": round(float(row["revenue"]), 2),
                "sharePct": round(float(row["share_pct"]), 2),
            }
            for _, row in payments.iterrows()
        ],
    }


def write_typescript(data, output_path: str):
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    content = "// AUTO-GENERATED FILE.\n"
    content += "// Source: prototype-data/teketeke_sales.csv\n"
    content += "// Generated by analytics/generate_dashboard_data.py\n"
    content += "// Do not manually edit this file.\n\n"
    content += "export const dashboardData = "
    content += json.dumps(data, indent=2)
    content += " as const;\n"
    output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    csv_path = sys.argv[1] if len(sys.argv) > 1 else "prototype-data/teketeke_sales.csv"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "data/teketeke_dashboard_data.ts"

    data = build_dashboard_data(csv_path)
    write_typescript(data, output_path)

    print("TEKETEKE DASHBOARD DATA")
    print("=" * 48)
    print(f"Source: {csv_path}")
    print(f"Output: {output_path}")
    print(f"Revenue: ${data['executive']['totalRevenue']:,.2f}")
    print(f"Gross profit: ${data['executive']['grossProfit']:,.2f}")
    print(f"Gross margin: {data['executive']['grossMarginPct']:.2f}%")
    print(f"Monthly records: {len(data['monthlyPerformance'])}")
    print(f"Countries: {len(data['countries'])}")
    print(f"Products: {len(data['products'])}")
    print(f"Customers included: {len(data['customers'])}")
    print("Generation complete.")
