// AUTO-GENERATED FILE.
// Source: prototype-data/teketeke_sales.csv
// Generated by analytics/generate_dashboard_data.py
// Do not manually edit this file.

export const dashboardData = {
  "executive": {
    "totalRevenue": 113371495.96,
    "totalCost": 69225551.09,
    "grossProfit": 44145944.87,
    "grossMarginPct": 38.94,
    "transactions": 10000,
    "customers": 80,
    "unitsSold": 41316
  },
  "monthlyPerformance": [
    {
      "month": "2024-01",
      "revenue": 4547490.1,
      "grossProfit": 1757252.75,
      "grossMarginPct": 38.64,
      "growthPct": 0.0
    },
    {
      "month": "2024-02",
      "revenue": 3973292.0,
      "grossProfit": 1590791.73,
      "grossMarginPct": 40.04,
      "growthPct": -0.13
    },
    {
      "month": "2024-03",
      "revenue": 5058786.17,
      "grossProfit": 1992112.15,
      "grossMarginPct": 39.38,
      "growthPct": 0.27
    },
    {
      "month": "2024-04",
      "revenue": 4426554.96,
      "grossProfit": 1735080.6,
      "grossMarginPct": 39.2,
      "growthPct": -0.12
    },
    {
      "month": "2024-05",
      "revenue": 4528519.8,
      "grossProfit": 1791888.44,
      "grossMarginPct": 39.57,
      "growthPct": 0.02
    },
    {
      "month": "2024-06",
      "revenue": 4561282.04,
      "grossProfit": 1769019.13,
      "grossMarginPct": 38.78,
      "growthPct": 0.01
    },
    {
      "month": "2024-07",
      "revenue": 4993324.34,
      "grossProfit": 1946921.21,
      "grossMarginPct": 38.99,
      "growthPct": 0.09
    },
    {
      "month": "2024-08",
      "revenue": 4155677.21,
      "grossProfit": 1587353.12,
      "grossMarginPct": 38.2,
      "growthPct": -0.17
    },
    {
      "month": "2024-09",
      "revenue": 4309716.67,
      "grossProfit": 1655345.72,
      "grossMarginPct": 38.41,
      "growthPct": 0.04
    },
    {
      "month": "2024-10",
      "revenue": 4491188.55,
      "grossProfit": 1758520.75,
      "grossMarginPct": 39.15,
      "growthPct": 0.04
    },
    {
      "month": "2024-11",
      "revenue": 4022657.06,
      "grossProfit": 1597768.13,
      "grossMarginPct": 39.72,
      "growthPct": -0.1
    },
    {
      "month": "2024-12",
      "revenue": 4560356.06,
      "grossProfit": 1813349.53,
      "grossMarginPct": 39.76,
      "growthPct": 0.13
    },
    {
      "month": "2025-01",
      "revenue": 4773143.26,
      "grossProfit": 1891369.41,
      "grossMarginPct": 39.63,
      "growthPct": 0.05
    },
    {
      "month": "2025-02",
      "revenue": 5118938.82,
      "grossProfit": 2007757.1,
      "grossMarginPct": 39.22,
      "growthPct": 0.07
    },
    {
      "month": "2025-03",
      "revenue": 5200589.8,
      "grossProfit": 2044400.36,
      "grossMarginPct": 39.31,
      "growthPct": 0.02
    },
    {
      "month": "2025-04",
      "revenue": 5382353.59,
      "grossProfit": 2109925.27,
      "grossMarginPct": 39.2,
      "growthPct": 0.03
    },
    {
      "month": "2025-05",
      "revenue": 5420549.01,
      "grossProfit": 2120158.47,
      "grossMarginPct": 39.11,
      "growthPct": 0.01
    },
    {
      "month": "2025-06",
      "revenue": 4777701.21,
      "grossProfit": 1830790.14,
      "grossMarginPct": 38.32,
      "growthPct": -0.12
    },
    {
      "month": "2025-07",
      "revenue": 4817723.94,
      "grossProfit": 1844141.96,
      "grossMarginPct": 38.28,
      "growthPct": 0.01
    },
    {
      "month": "2025-08",
      "revenue": 5318429.66,
      "grossProfit": 2029941.61,
      "grossMarginPct": 38.17,
      "growthPct": 0.1
    },
    {
      "month": "2025-09",
      "revenue": 4343812.0,
      "grossProfit": 1688011.43,
      "grossMarginPct": 38.86,
      "growthPct": -0.18
    },
    {
      "month": "2025-10",
      "revenue": 5370322.58,
      "grossProfit": 2026109.17,
      "grossMarginPct": 37.73,
      "growthPct": 0.24
    },
    {
      "month": "2025-11",
      "revenue": 4498575.76,
      "grossProfit": 1740795.79,
      "grossMarginPct": 38.7,
      "growthPct": -0.16
    },
    {
      "month": "2025-12",
      "revenue": 4720511.37,
      "grossProfit": 1817140.9,
      "grossMarginPct": 38.49,
      "growthPct": 0.05
    }
  ],
  "countries": [
    {
      "name": "Kenya",
      "revenue": 48917938.87,
      "sharePct": 43.15
    },
    {
      "name": "Uganda",
      "revenue": 21340513.4,
      "sharePct": 18.82
    },
    {
      "name": "Tanzania",
      "revenue": 19913096.13,
      "sharePct": 17.56
    },
    {
      "name": "Rwanda",
      "revenue": 14917565.95,
      "sharePct": 13.16
    },
    {
      "name": "South Sudan",
      "revenue": 8282381.61,
      "sharePct": 7.31
    }
  ],
  "products": [
    {
      "name": "Carrier Router",
      "revenue": 30348252.28,
      "grossProfit": 10982076.4,
      "grossMarginPct": 36.19
    },
    {
      "name": "Enterprise Firewall",
      "revenue": 23006523.12,
      "grossProfit": 9845401.86,
      "grossMarginPct": 42.79
    },
    {
      "name": "Core Switch",
      "revenue": 19743184.77,
      "grossProfit": 7158458.1,
      "grossMarginPct": 36.26
    },
    {
      "name": "Fiber OLT",
      "revenue": 17594032.43,
      "grossProfit": 5481091.09,
      "grossMarginPct": 31.15
    },
    {
      "name": "Enterprise Router",
      "revenue": 8429803.85,
      "grossProfit": 3115491.95,
      "grossMarginPct": 36.96
    },
    {
      "name": "Network Support",
      "revenue": 7236334.03,
      "grossProfit": 4848836.1,
      "grossMarginPct": 67.01
    },
    {
      "name": "Managed Switch",
      "revenue": 4204255.52,
      "grossProfit": 1654866.93,
      "grossMarginPct": 39.36
    },
    {
      "name": "Wireless Access Point",
      "revenue": 1958105.76,
      "grossProfit": 806266.18,
      "grossMarginPct": 41.18
    },
    {
      "name": "Optical Transceiver",
      "revenue": 851004.2,
      "grossProfit": 253456.26,
      "grossMarginPct": 29.78
    }
  ],
  "customers": [
    {
      "name": "Customer 001",
      "revenue": 25137003.89,
      "sharePct": 22.17
    },
    {
      "name": "Customer 064",
      "revenue": 1518487.09,
      "sharePct": 1.34
    },
    {
      "name": "Customer 015",
      "revenue": 1493494.25,
      "sharePct": 1.32
    },
    {
      "name": "Customer 049",
      "revenue": 1428676.83,
      "sharePct": 1.26
    },
    {
      "name": "Customer 019",
      "revenue": 1416240.97,
      "sharePct": 1.25
    },
    {
      "name": "Customer 003",
      "revenue": 1415004.3,
      "sharePct": 1.25
    },
    {
      "name": "Customer 021",
      "revenue": 1363560.77,
      "sharePct": 1.2
    },
    {
      "name": "Customer 065",
      "revenue": 1355141.95,
      "sharePct": 1.2
    },
    {
      "name": "Customer 029",
      "revenue": 1342157.62,
      "sharePct": 1.18
    },
    {
      "name": "Customer 042",
      "revenue": 1318171.3,
      "sharePct": 1.16
    },
    {
      "name": "Customer 072",
      "revenue": 1312743.7,
      "sharePct": 1.16
    },
    {
      "name": "Customer 052",
      "revenue": 1309525.69,
      "sharePct": 1.16
    },
    {
      "name": "Customer 014",
      "revenue": 1307991.72,
      "sharePct": 1.15
    },
    {
      "name": "Customer 048",
      "revenue": 1285411.9,
      "sharePct": 1.13
    },
    {
      "name": "Customer 069",
      "revenue": 1278239.5,
      "sharePct": 1.13
    }
  ],
  "payments": [
    {
      "status": "Paid",
      "revenue": 88271000.71,
      "sharePct": 77.86
    },
    {
      "status": "Pending",
      "revenue": 15065383.94,
      "sharePct": 13.29
    },
    {
      "status": "Overdue",
      "revenue": 10035111.31,
      "sharePct": 8.85
    }
  ]
} as const;
